version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea:latest
    container_name: gitea
    env_file:
      - .env
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=${GITEA_NAME}
      - GITEA__database__USER=${GITEA_USER}
      - GITEA__database__PASSWD=${GITEA_PASSWD}
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:Europe/Paris
      - /etc/localtime:/etc/localtime:Europe/Paris
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db

  db:
    image: mariadb
    restart: always
    container_name: ap42-git
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    networks:
      - gitea
    volumes:
      - ./mariadb:/var/lib/mariadb
